// Re-export the canonical BackendContract and all supporting types
// from the main-process definition. The renderer imports from this
// module so it never depends on main-process internals directly.

export type {
  Credentials,
  AuthResult,
  User,
  NewProjectParams,
  Project,
  CasePlanModelRef,
  DomainContextRef,
  RecentProject,
  CasePlanModelSummary,
  CasePlanModel,
  CasePlanModelNode,
  CasePlanModelEdge,
  Stage,
  Milestone,
  Sentry,
  SentryCondition,
  CaseVariable,
  DomainContextBinding,
  ValidationResult,
  ValidationError,
  ValidationWarning,
  PublishParams,
  PublishResult,
  DomainContextSummary,
  DomainContext,
  DomainContextOrigin,
  TestScenarioParams,
  TestRunId,
  TestEvent,
  TestScenario,
  TestStep,
  TestExpectedOutcome,
  BackendContract,
} from '../../src-main/backend/contract'
